# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macos-10.15'

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false    

- task: Gradle@2
  displayName: 'gradlew assembleRelease'
  inputs:
    gradleWrapperFile: android/gradlew
    workingDirectory: android
    tasks: assembleRelease

- task: CopyFiles@2
  displayName: 'Copy APK file'
  inputs:
    SourceFolder: android/app/build/outputs/apk/release
    Contents: 'app-release.apk'
    TargetFolder: '$(build.artifactstagingdirectory)/ffh_$(Build.BuildID).apk'
    CleanTargetFolder: true
    OverWrite: true
    flattenFolders: true